#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsProcesses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ServiceAdmin")]
	public partial class ServiceAdminDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSalesOrderReference(SalesOrderReference instance);
    partial void UpdateSalesOrderReference(SalesOrderReference instance);
    partial void DeleteSalesOrderReference(SalesOrderReference instance);
    partial void InsertReferenceValue(ReferenceValue instance);
    partial void UpdateReferenceValue(ReferenceValue instance);
    partial void DeleteReferenceValue(ReferenceValue instance);
    #endregion
		
		public ServiceAdminDataContext() : 
				base(global::DynamicsProcesses.Properties.Settings.Default.ServiceAdminConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceAdminDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceAdminDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceAdminDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceAdminDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SalesOrderReference> SalesOrderReferences
		{
			get
			{
				return this.GetTable<SalesOrderReference>();
			}
		}
		
		public System.Data.Linq.Table<ReferenceValue> ReferenceValues
		{
			get
			{
				return this.GetTable<ReferenceValue>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_getOrgsFlaggedFraudReview")]
		public ISingleResult<usp_getOrgsFlaggedFraudReviewResult> usp_getOrgsFlaggedFraudReview([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date);
			return ((ISingleResult<usp_getOrgsFlaggedFraudReviewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_findOrgMatches")]
		public ISingleResult<usp_findOrgMatchesResult> usp_findOrgMatches([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tsOrgId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tsOrgId);
			return ((ISingleResult<usp_findOrgMatchesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_orgsWithOrders")]
		public ISingleResult<usp_orgsWithOrdersResult> usp_orgsWithOrders([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string tsOrgIds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tsOrgIds);
			return ((ISingleResult<usp_orgsWithOrdersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_getOrgOrderElig_newAC")]
		public ISingleResult<usp_getOrgOrderElig_newACResult> usp_getOrgOrderElig_newAC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tsOrgId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string alternateActivityCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tsOrgId, alternateActivityCode);
			return ((ISingleResult<usp_getOrgOrderElig_newACResult>)(result.ReturnValue));
		}



        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.usp_getUserRegIpAddress")]
        public ISingleResult<usp_getUserRegIpAddressResult> usp_getUserRegIpAddress([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "NVarChar(250)")] string email)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
            return ((ISingleResult<usp_getUserRegIpAddressResult>)(result.ReturnValue));
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalesOrderReference")]
	public partial class SalesOrderReference : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OrderNumber;
		
		private string _ReferenceType;
		
		private string _ReferenceValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnReferenceTypeChanging(string value);
    partial void OnReferenceTypeChanged();
    partial void OnReferenceValueChanging(string value);
    partial void OnReferenceValueChanged();
    #endregion
		
		public SalesOrderReference()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="VarChar(50)")]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceType", DbType="VarChar(100)")]
		public string ReferenceType
		{
			get
			{
				return this._ReferenceType;
			}
			set
			{
				if ((this._ReferenceType != value))
				{
					this.OnReferenceTypeChanging(value);
					this.SendPropertyChanging();
					this._ReferenceType = value;
					this.SendPropertyChanged("ReferenceType");
					this.OnReferenceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceValue", DbType="NVarChar(500)")]
		public string ReferenceValue
		{
			get
			{
				return this._ReferenceValue;
			}
			set
			{
				if ((this._ReferenceValue != value))
				{
					this.OnReferenceValueChanging(value);
					this.SendPropertyChanging();
					this._ReferenceValue = value;
					this.SendPropertyChanged("ReferenceValue");
					this.OnReferenceValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReferenceValues")]
	public partial class ReferenceValue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ReferenceId;
		
		private string _InsertedBy;
		
		private System.DateTime _InsertedDate;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedDate;
		
		private string _ReferenceGroup;
		
		private string _ReferenceType;
		
		private string _ReferenceName;
		
		private string _ReferenceValue1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReferenceIdChanging(string value);
    partial void OnReferenceIdChanged();
    partial void OnInsertedByChanging(string value);
    partial void OnInsertedByChanged();
    partial void OnInsertedDateChanging(System.DateTime value);
    partial void OnInsertedDateChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedDateChanging(System.DateTime value);
    partial void OnUpdatedDateChanged();
    partial void OnReferenceGroupChanging(string value);
    partial void OnReferenceGroupChanged();
    partial void OnReferenceTypeChanging(string value);
    partial void OnReferenceTypeChanged();
    partial void OnReferenceNameChanging(string value);
    partial void OnReferenceNameChanged();
    partial void OnReferenceValue1Changing(string value);
    partial void OnReferenceValue1Changed();
    #endregion
		
		public ReferenceValue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceId", DbType="Char(38) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ReferenceId
		{
			get
			{
				return this._ReferenceId;
			}
			set
			{
				if ((this._ReferenceId != value))
				{
					this.OnReferenceIdChanging(value);
					this.SendPropertyChanging();
					this._ReferenceId = value;
					this.SendPropertyChanged("ReferenceId");
					this.OnReferenceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InsertedBy
		{
			get
			{
				return this._InsertedBy;
			}
			set
			{
				if ((this._InsertedBy != value))
				{
					this.OnInsertedByChanging(value);
					this.SendPropertyChanging();
					this._InsertedBy = value;
					this.SendPropertyChanged("InsertedBy");
					this.OnInsertedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedDate", DbType="DateTime NOT NULL")]
		public System.DateTime InsertedDate
		{
			get
			{
				return this._InsertedDate;
			}
			set
			{
				if ((this._InsertedDate != value))
				{
					this.OnInsertedDateChanging(value);
					this.SendPropertyChanging();
					this._InsertedDate = value;
					this.SendPropertyChanged("InsertedDate");
					this.OnInsertedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceGroup", DbType="VarChar(50)")]
		public string ReferenceGroup
		{
			get
			{
				return this._ReferenceGroup;
			}
			set
			{
				if ((this._ReferenceGroup != value))
				{
					this.OnReferenceGroupChanging(value);
					this.SendPropertyChanging();
					this._ReferenceGroup = value;
					this.SendPropertyChanged("ReferenceGroup");
					this.OnReferenceGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceType", DbType="VarChar(50)")]
		public string ReferenceType
		{
			get
			{
				return this._ReferenceType;
			}
			set
			{
				if ((this._ReferenceType != value))
				{
					this.OnReferenceTypeChanging(value);
					this.SendPropertyChanging();
					this._ReferenceType = value;
					this.SendPropertyChanged("ReferenceType");
					this.OnReferenceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceName", DbType="VarChar(50)")]
		public string ReferenceName
		{
			get
			{
				return this._ReferenceName;
			}
			set
			{
				if ((this._ReferenceName != value))
				{
					this.OnReferenceNameChanging(value);
					this.SendPropertyChanging();
					this._ReferenceName = value;
					this.SendPropertyChanged("ReferenceName");
					this.OnReferenceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ReferenceValue", Storage="_ReferenceValue1", DbType="VarChar(50)")]
		public string ReferenceValue1
		{
			get
			{
				return this._ReferenceValue1;
			}
			set
			{
				if ((this._ReferenceValue1 != value))
				{
					this.OnReferenceValue1Changing(value);
					this.SendPropertyChanging();
					this._ReferenceValue1 = value;
					this.SendPropertyChanged("ReferenceValue1");
					this.OnReferenceValue1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class usp_getOrgsFlaggedFraudReviewResult
	{
		
		private System.Guid _note_id;
		
		private int _site_id;
		
		private string _secondary_id;
		
		private int _identity_id;
		
		private int _owner_id;
		
		private int _owner_type_enum;
		
		private string _note_desc;
		
		private string _text;
		
		private bool _read_only_access;
		
		private bool _private_access;
		
		private string _insert_by;
		
		private System.DateTime _insert_date;
		
		private string _update_by;
		
		private System.DateTime _update_date;
		
		private byte _delete_status;
		
		public usp_getOrgsFlaggedFraudReviewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid note_id
		{
			get
			{
				return this._note_id;
			}
			set
			{
				if ((this._note_id != value))
				{
					this._note_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_id", DbType="Int NOT NULL")]
		public int site_id
		{
			get
			{
				return this._site_id;
			}
			set
			{
				if ((this._site_id != value))
				{
					this._site_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondary_id", DbType="NVarChar(255)")]
		public string secondary_id
		{
			get
			{
				return this._secondary_id;
			}
			set
			{
				if ((this._secondary_id != value))
				{
					this._secondary_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identity_id", DbType="Int NOT NULL")]
		public int identity_id
		{
			get
			{
				return this._identity_id;
			}
			set
			{
				if ((this._identity_id != value))
				{
					this._identity_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_id", DbType="Int NOT NULL")]
		public int owner_id
		{
			get
			{
				return this._owner_id;
			}
			set
			{
				if ((this._owner_id != value))
				{
					this._owner_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_type_enum", DbType="Int NOT NULL")]
		public int owner_type_enum
		{
			get
			{
				return this._owner_type_enum;
			}
			set
			{
				if ((this._owner_type_enum != value))
				{
					this._owner_type_enum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note_desc", DbType="NVarChar(255)")]
		public string note_desc
		{
			get
			{
				return this._note_desc;
			}
			set
			{
				if ((this._note_desc != value))
				{
					this._note_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this._text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_read_only_access", DbType="Bit NOT NULL")]
		public bool read_only_access
		{
			get
			{
				return this._read_only_access;
			}
			set
			{
				if ((this._read_only_access != value))
				{
					this._read_only_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_private_access", DbType="Bit NOT NULL")]
		public bool private_access
		{
			get
			{
				return this._private_access;
			}
			set
			{
				if ((this._private_access != value))
				{
					this._private_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_by", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string insert_by
		{
			get
			{
				return this._insert_by;
			}
			set
			{
				if ((this._insert_by != value))
				{
					this._insert_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="DateTime NOT NULL")]
		public System.DateTime insert_date
		{
			get
			{
				return this._insert_date;
			}
			set
			{
				if ((this._insert_date != value))
				{
					this._insert_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_by", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string update_by
		{
			get
			{
				return this._update_by;
			}
			set
			{
				if ((this._update_by != value))
				{
					this._update_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime NOT NULL")]
		public System.DateTime update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this._update_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_status", DbType="TinyInt NOT NULL")]
		public byte delete_status
		{
			get
			{
				return this._delete_status;
			}
			set
			{
				if ((this._delete_status != value))
				{
					this._delete_status = value;
				}
			}
		}
	}
	
	public partial class usp_findOrgMatchesResult
	{
		
		private string _orgMatches;
		
		public usp_findOrgMatchesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgMatches", DbType="VarChar(4000)")]
		public string orgMatches
		{
			get
			{
				return this._orgMatches;
			}
			set
			{
				if ((this._orgMatches != value))
				{
					this._orgMatches = value;
				}
			}
		}
	}
	
	public partial class usp_orgsWithOrdersResult
	{
		
		private string _tsOrgId;
		
		private System.Nullable<bool> _hasOrders;
		
		public usp_orgsWithOrdersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsOrgId", DbType="VarChar(MAX)")]
		public string tsOrgId
		{
			get
			{
				return this._tsOrgId;
			}
			set
			{
				if ((this._tsOrgId != value))
				{
					this._tsOrgId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasOrders", DbType="Bit")]
		public System.Nullable<bool> hasOrders
		{
			get
			{
				return this._hasOrders;
			}
			set
			{
				if ((this._hasOrders != value))
				{
					this._hasOrders = value;
				}
			}
		}
	}
	
	public partial class usp_getOrgOrderElig_newACResult
	{
		
		private System.Nullable<bool> _isActivityCodeElig;
		
		public usp_getOrgOrderElig_newACResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActivityCodeElig", DbType="Bit")]
		public System.Nullable<bool> isActivityCodeElig
		{
			get
			{
				return this._isActivityCodeElig;
			}
			set
			{
				if ((this._isActivityCodeElig != value))
				{
					this._isActivityCodeElig = value;
				}
			}
		}
	}


    public partial class usp_getUserRegIpAddressResult
    {

        private string _userIpAddress;

        public usp_getUserRegIpAddressResult()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_userIpAddress", DbType = "NVarChar(250)")]
        public string userIpAddress
        {
            get
            {
                return this._userIpAddress;
            }
            set
            {
                if ((this._userIpAddress != value))
                {
                    this._userIpAddress = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
