//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDServices.DataAccessService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://techsoupglobal.org/DataAccessService/", ConfigurationName="DataAccessService.DataAccessService")]
    public interface DataAccessService {
        
        // CODEGEN: Generating message contract since the operation ExecuteStoredProc is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://techsoupglobal.org/DataAccessService/ExecuteStoredProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDServices.DataAccessService.executeStoredProcResponse ExecuteStoredProc(EDServices.DataAccessService.executeStoredProcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://techsoupglobal.org/DataAccessService/ExecuteStoredProc", ReplyAction="*")]
        System.Threading.Tasks.Task<EDServices.DataAccessService.executeStoredProcResponse> ExecuteStoredProcAsync(EDServices.DataAccessService.executeStoredProcRequest request);
        
        // CODEGEN: Generating message contract since the operation ExecuteStoredProcReturnRecordsets is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://techsoupglobal.org/DataAccessService/ExecuteStoredProcReturnRecordsets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EDServices.DataAccessService.executeReturnRecordsetsResponse ExecuteStoredProcReturnRecordsets(EDServices.DataAccessService.executeStoredProcWithRecordsetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://techsoupglobal.org/DataAccessService/ExecuteStoredProcReturnRecordsets", ReplyAction="*")]
        System.Threading.Tasks.Task<EDServices.DataAccessService.executeReturnRecordsetsResponse> ExecuteStoredProcReturnRecordsetsAsync(EDServices.DataAccessService.executeStoredProcWithRecordsetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://techsoupglobal.org/DataAccessService/")]
    public partial class ExecuteStoredProcRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverNameField;
        
        private string dBNameField;
        
        private string sPNameField;
        
        private inputParamsType paramsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
                this.RaisePropertyChanged("ServerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DBName {
            get {
                return this.dBNameField;
            }
            set {
                this.dBNameField = value;
                this.RaisePropertyChanged("DBName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SPName {
            get {
                return this.sPNameField;
            }
            set {
                this.sPNameField = value;
                this.RaisePropertyChanged("SPName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public inputParamsType @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://techsoupglobal.org/DataAccessService/")]
    public partial class inputParamsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.techsoupglobal.org/dbcalloutservice/")]
    public partial class recordsetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private rowType[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public rowType[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.techsoupglobal.org/dbcalloutservice/")]
    public partial class rowType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://techsoupglobal.org/DataAccessService/")]
    public partial class ExecuteStoredProcResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceNameField;
        
        private string actionNameField;
        
        private string resultStatusField;
        
        private rowType[] returnXmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ActionName {
            get {
                return this.actionNameField;
            }
            set {
                this.actionNameField = value;
                this.RaisePropertyChanged("ActionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
                this.RaisePropertyChanged("ResultStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public rowType[] ReturnXml {
            get {
                return this.returnXmlField;
            }
            set {
                this.returnXmlField = value;
                this.RaisePropertyChanged("ReturnXml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeStoredProcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteStoredProcRequest", Namespace="http://techsoupglobal.org/DataAccessService/", Order=0)]
        public EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcRequest1;
        
        public executeStoredProcRequest() {
        }
        
        public executeStoredProcRequest(EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcRequest1) {
            this.ExecuteStoredProcRequest1 = ExecuteStoredProcRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeStoredProcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteStoredProcResponse", Namespace="http://techsoupglobal.org/DataAccessService/", Order=0)]
        public EDServices.DataAccessService.ExecuteStoredProcResponseType ExecuteStoredProcResponse1;
        
        public executeStoredProcResponse() {
        }
        
        public executeStoredProcResponse(EDServices.DataAccessService.ExecuteStoredProcResponseType ExecuteStoredProcResponse1) {
            this.ExecuteStoredProcResponse1 = ExecuteStoredProcResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://techsoupglobal.org/DataAccessService/")]
    public partial class ExecuteStoredProcReturnRecordsetsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceField;
        
        private string operationField;
        
        private string resultStatusField;
        
        private recordsetType[] returnXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("Service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
                this.RaisePropertyChanged("ResultStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("recordset", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public recordsetType[] ReturnXML {
            get {
                return this.returnXMLField;
            }
            set {
                this.returnXMLField = value;
                this.RaisePropertyChanged("ReturnXML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeStoredProcWithRecordsetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://techsoupglobal.org/DataAccessService/", Order=0)]
        public EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcReturnRecordsetsRequest;
        
        public executeStoredProcWithRecordsetRequest() {
        }
        
        public executeStoredProcWithRecordsetRequest(EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcReturnRecordsetsRequest) {
            this.ExecuteStoredProcReturnRecordsetsRequest = ExecuteStoredProcReturnRecordsetsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeReturnRecordsetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://techsoupglobal.org/DataAccessService/", Order=0)]
        public EDServices.DataAccessService.ExecuteStoredProcReturnRecordsetsResponse ExecuteStoredProcReturnRecordsetsResponse;
        
        public executeReturnRecordsetsResponse() {
        }
        
        public executeReturnRecordsetsResponse(EDServices.DataAccessService.ExecuteStoredProcReturnRecordsetsResponse ExecuteStoredProcReturnRecordsetsResponse) {
            this.ExecuteStoredProcReturnRecordsetsResponse = ExecuteStoredProcReturnRecordsetsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataAccessServiceChannel : EDServices.DataAccessService.DataAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataAccessServiceClient : System.ServiceModel.ClientBase<EDServices.DataAccessService.DataAccessService>, EDServices.DataAccessService.DataAccessService {
        
        public DataAccessServiceClient() {
        }
        
        public DataAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDServices.DataAccessService.executeStoredProcResponse EDServices.DataAccessService.DataAccessService.ExecuteStoredProc(EDServices.DataAccessService.executeStoredProcRequest request) {
            return base.Channel.ExecuteStoredProc(request);
        }
        
        public EDServices.DataAccessService.ExecuteStoredProcResponseType ExecuteStoredProc(EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcRequest1) {
            EDServices.DataAccessService.executeStoredProcRequest inValue = new EDServices.DataAccessService.executeStoredProcRequest();
            inValue.ExecuteStoredProcRequest1 = ExecuteStoredProcRequest1;
            EDServices.DataAccessService.executeStoredProcResponse retVal = ((EDServices.DataAccessService.DataAccessService)(this)).ExecuteStoredProc(inValue);
            return retVal.ExecuteStoredProcResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDServices.DataAccessService.executeStoredProcResponse> EDServices.DataAccessService.DataAccessService.ExecuteStoredProcAsync(EDServices.DataAccessService.executeStoredProcRequest request) {
            return base.Channel.ExecuteStoredProcAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDServices.DataAccessService.executeStoredProcResponse> ExecuteStoredProcAsync(EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcRequest1) {
            EDServices.DataAccessService.executeStoredProcRequest inValue = new EDServices.DataAccessService.executeStoredProcRequest();
            inValue.ExecuteStoredProcRequest1 = ExecuteStoredProcRequest1;
            return ((EDServices.DataAccessService.DataAccessService)(this)).ExecuteStoredProcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDServices.DataAccessService.executeReturnRecordsetsResponse EDServices.DataAccessService.DataAccessService.ExecuteStoredProcReturnRecordsets(EDServices.DataAccessService.executeStoredProcWithRecordsetRequest request) {
            return base.Channel.ExecuteStoredProcReturnRecordsets(request);
        }
        
        public EDServices.DataAccessService.ExecuteStoredProcReturnRecordsetsResponse ExecuteStoredProcReturnRecordsets(EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcReturnRecordsetsRequest) {
            EDServices.DataAccessService.executeStoredProcWithRecordsetRequest inValue = new EDServices.DataAccessService.executeStoredProcWithRecordsetRequest();
            inValue.ExecuteStoredProcReturnRecordsetsRequest = ExecuteStoredProcReturnRecordsetsRequest;
            EDServices.DataAccessService.executeReturnRecordsetsResponse retVal = ((EDServices.DataAccessService.DataAccessService)(this)).ExecuteStoredProcReturnRecordsets(inValue);
            return retVal.ExecuteStoredProcReturnRecordsetsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDServices.DataAccessService.executeReturnRecordsetsResponse> EDServices.DataAccessService.DataAccessService.ExecuteStoredProcReturnRecordsetsAsync(EDServices.DataAccessService.executeStoredProcWithRecordsetRequest request) {
            return base.Channel.ExecuteStoredProcReturnRecordsetsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDServices.DataAccessService.executeReturnRecordsetsResponse> ExecuteStoredProcReturnRecordsetsAsync(EDServices.DataAccessService.ExecuteStoredProcRequestType ExecuteStoredProcReturnRecordsetsRequest) {
            EDServices.DataAccessService.executeStoredProcWithRecordsetRequest inValue = new EDServices.DataAccessService.executeStoredProcWithRecordsetRequest();
            inValue.ExecuteStoredProcReturnRecordsetsRequest = ExecuteStoredProcReturnRecordsetsRequest;
            return ((EDServices.DataAccessService.DataAccessService)(this)).ExecuteStoredProcReturnRecordsetsAsync(inValue);
        }
    }
}
